name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code từ repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Cài đặt Node.js + Cache npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Cài đặt Java JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      # 4. Tự động Cache Gradle (Giúp tăng tốc từ lần build sau)
      - name: Setup Gradle Cache
        uses: gradle/actions/setup-gradle@v3

      # 5. Cài đặt Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 6. Cài đặt dependencies
      - name: Install dependencies
        run: npm install

      # 7. Prebuild Android project
      - name: Prebuild Android project
        run: npx expo prebuild --platform android

      # 8. Cấp quyền thực thi cho gradlew
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # 9. Build APK - CHỈ biên dịch cho chip arm64-v8a (Siêu nhanh & Siêu nhẹ)
      - name: Build Android Release APK
        run: |
          cd android
          ./gradlew assembleRelease -PreactNativeArchitectures=arm64-v8a

      # 10. Upload file APK
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-release
          path: android/app/build/outputs/apk/release/*.apk